security:
  jwt:
    token:
      secret-key: 53cr37

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dnd_account
    username: root
    password: 1123581321asG!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto:
    show-sql: false
springdoc:
  pathsToMatch:
  swagger-ui:
    use-root-path: true

  application:
    name: DnDAccountApplication