CREATE TABLE IF NOT EXISTS `characters` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `account_username` varchar(40) NOT NULL,
  `name` varchar(40) DEFAULT NULL,
  `strength` INTEGER NOT NULL,
  `constitution` INTEGER NOT NULL,
  `dexterity` INTEGER NOT NULL,
  `wisdom` INTEGER NOT NULL,
  `intelligence` INTEGER NOT NULL,
  `charisma` INTEGER NOT NULL,
  `character_level` INTEGER,
  `character_class` varchar(20) NOT NULL,
  `subclass` varchar(20),
  `class_level` INTEGER NOT NULL,
  `multiclass` BIT(1) NOT NULL,
  `character_multiclass` varchar(20),
  `multiclass_subclass` varchar(20),
  `multiclass_level`INTEGER,
  `life` INTEGER,
  `armor_class` INTEGER NOT NULL,
  `gold` INTEGER,
  `armor` varchar(20),
  `weapon` varchar(255),
  `treasure` varchar(255),
  PRIMARY KEY (`id`)
  );